spring:
  application:
    name: SmartTextBook
  profiles:
    active: server-dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 确保使用 AntPathMatcher 进行路径匹配

files:
  path: upload/public/picture
  apkpath: /opt/apkfile
